"""created indexes

Revision ID: 870952857984
Revises: 7a45c9ed98d6
Create Date: 2023-11-19 23:11:27.107713

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '870952857984'
down_revision = '7a45c9ed98d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f('ix_user_notify_settings_user_telegram_id'),
        'user_notify_settings',
        ['user_telegram_id'],
        unique=True,
    )
    op.create_index(
        op.f('ix_user_status_user_telegram_id'),
        'user_status',
        ['user_telegram_id'],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_user_status_user_telegram_id'), table_name='user_status'
    )
    op.drop_index(
        op.f('ix_user_notify_settings_user_telegram_id'),
        table_name='user_notify_settings',
    )
    # ### end Alembic commands ###
