services:
  postgres:
    image: postgres:14.13-alpine
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    networks:
      - omb-net
    volumes:
      - $PWD/postgres_volume:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: "omb_database"
      POSTGRES_USER: "omb_user"
      POSTGRES_PASSWORD: "${SQL_PASSWORD}"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U omb_user -d omb_database'" ]
      interval: 10s
      timeout: 3s
      retries: 3

  rabbitmq:
    build: $PWD/rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ messaging port
      - "15672:15672" # RabbitMQ management console port
      - "15692:15692" # RabbitMQ management console prometheus plugin port
    networks:
      - omb-net
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648"
      RABBITMQ_PLUGINS: "rabbitmq_prometheus"
    volumes:
      - $PWD/rabbitmq_volume:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  mongodb:
    # image: mongo:7.0
    build: $PWD/mongodb
    container_name: mongodb
    hostname: mongodb
    ports:
      - "27017:27017"
    networks:
      - omb-net
    volumes:
      - $PWD/mongodb_volume:/data/db
      - $PWD/mongodb/mongo-rs-initiate.js:/docker-entrypoint-initdb.d/rs-initiate.js
    command: ["--replSet", "rs0", "--bind_ip_all"]
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 3

  # mongo-express:
  #   image: mongo-express:1.0.2
  #   container_name: mongo-express
  #   depends_on:
  #     mongodb:
  #       condition: service_healthy
  #   ports:
  #     - "8081:8081"
  #   expose:
  #     - 8081
  #   environment:
  #     # ME_CONFIG_MONGODB_URL: "mongodb://mongodb:27017"
  #     ME_CONFIG_MONGODB_URL: "mongodb://host.docker.internal:27017"
  #     ME_CONFIG_BASICAUTH_USERNAME: "admin"
  #     ME_CONFIG_BASICAUTH_PASSWORD: "admin"
  #   volumes:
  #     - $PWD/mongo-express_healthcheck.sh:/mongo-express_healthcheck.sh
  #   healthcheck:
  #     test: ["CMD", "./mongo-express_healthcheck.sh"]
  #     interval: 10s
  #     timeout: 10s
  #     retries: 3

  # prometheus:
  #   image: prom/prometheus:v2.30.3
  #   container_name: prometheus
  #   hostname: prometheus
  #   networks:
  #     - prometheus
  #   ports:
  #     - "9090:9090" # Prometheus web UI port
  #   volumes:
  #     - $PWD/prometheus.yml:/etc/prometheus/prometheus.yml
  #   command:
  #     - "--config.file=/etc/prometheus/prometheus.yml"
  #   # TODO: healthcheck

  # grafana:
  #   image: grafana/grafana:latest
  #   ports:
  #     - "3000:3000" # Grafana web UI port
  #   networks:
  #     - prometheus
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=admin # Set your desired Grafana admin password here
  #   volumes:
  #     - $PWD/grafana_volume:/var/alpinelib/grafana
  #   healthcheck:
  #     test: [ "CMD-SHELL", "curl -f localhost:3000/api/health && echo 'ready'" ]
  #     interval: 10s
  #     retries: 30

  # dozzle:
  #   image: amir20/dozzle:latest
  #   environment:
  #     DOZZLE_USERNAME: "admin"
  #     DOZZLE_PASSWORD: "admin"
  #     DOZZLE_NO_ANALYTICS: "true"
  #     DOZZLE_LEVEL: "info"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   ports:
  #     - "8080:8080"
  #   restart: unless-stopped



networks:
  omb-net:
    external: true
