[SERVICE]
    flush 1
    log_level info
    parsers_file parsers.conf
    storage.path /tmp/flb-storage/
    storage.sync normal
    storage.backlog.mem_limit 100M

[INPUT]
    Name tail
    Path /logs/orioks-requester/*.log
    Tag app.orioks-requester
    Parser json_parser
    Refresh_Interval 2
    Rotate_Wait 30
    Skip_Long_Lines On
    Skip_Empty_Lines On
    Mem_Buf_Limit 50MB
    storage.type filesystem
    Read_from_Head On

[INPUT]
    Name tail
    Path /logs/checking/*.log
    Tag app.checking
    Parser json_parser
    Refresh_Interval 2
    Rotate_Wait 30
    Skip_Long_Lines On
    Skip_Empty_Lines On
    Mem_Buf_Limit 50MB
    storage.type filesystem
    Read_from_Head On

[INPUT]
    Name tail
    Path /logs/bot/*.log
    Tag app.bot
    Parser json_parser
    Refresh_Interval 2
    Rotate_Wait 30
    Skip_Long_Lines On
    Skip_Empty_Lines On
    Mem_Buf_Limit 50MB
    storage.type filesystem
    Read_from_Head On

[INPUT]
    Name tail
    Path /logs/login-logout/*.log
    Tag app.login-logout
    Parser json_parser
    Refresh_Interval 2
    Rotate_Wait 30
    Skip_Long_Lines On
    Skip_Empty_Lines On
    Mem_Buf_Limit 50MB
    storage.type filesystem
    Read_from_Head On

[INPUT]
    Name tail
    Path /logs/notifier/*.log
    Tag app.notifier
    Parser json_parser
    Refresh_Interval 2
    Rotate_Wait 30
    Skip_Long_Lines On
    Skip_Empty_Lines On
    Mem_Buf_Limit 50MB
    storage.type filesystem
    Read_from_Head On

[FILTER]
    Name modify
    Match app.*
    Add agent fluent-bit
    Add environment production
    Add log_type application

[OUTPUT]
    Name loki
    Match app.orioks-requester
    Host loki
    Port 3100
    Labels agent=fluent-bit,service=orioks-requester,log_type=application
    Retry_Limit 3

[OUTPUT]
    Name loki
    Match app.checking
    Host loki
    Port 3100
    Labels agent=fluent-bit,service=checking,log_type=application
    Retry_Limit 3

[OUTPUT]
    Name loki
    Match app.bot
    Host loki
    Port 3100
    Labels agent=fluent-bit,service=bot,log_type=application
    Retry_Limit 3

[OUTPUT]
    Name loki
    Match app.login-logout
    Host loki
    Port 3100
    Labels agent=fluent-bit,service=login-logout,log_type=application
    Retry_Limit 3

[OUTPUT]
    Name loki
    Match app.notifier
    Host loki
    Port 3100
    Labels agent=fluent-bit,service=notifier,log_type=application
    Retry_Limit 3

[OUTPUT]
    Name stdout
    Match app.*
    Format json
